In [1]:
import numpy as np

## Data Types and Attribute 

### NumPy's main datatype is ndarray (n dimensional array)

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
 a1.shape
    

(4,)

In [8]:
a1.ndim


1

### Create arrays


In [11]:
sample_array = np.array([[1,2,3],[4,5,6]])
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ones = np.ones((2,4),dtype=int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
zeros = np.zeros((2,2,2,2))
zeros

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [14]:
random_array = np.random.randint(0,10,size=(2,3)) 

In [15]:
random_array

array([[1, 6, 1],
       [5, 3, 8]])