In [3]:
import numpy as np

## Data Types and Attribute 

### NumPy's main datatype is ndarray (n dimensional array)

In [4]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [67]:
a2 = np.array([[1, 2, 3.3],[4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [68]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
type(a1)

numpy.ndarray

In [6]:
 a1.shape
    

(4,)

In [7]:
a1.ndim


1

### Create arrays


In [8]:
sample_array = np.array([[1,2,3],[4,5,6]])
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
ones = np.ones((2,4),dtype=int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
zeros = np.zeros((2,2,2,2))
zeros

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [11]:
random_array = np.random.randint(0,10,size=(2,3)) 

In [12]:
random_array

array([[9, 3, 9],
       [4, 5, 7]])

In [54]:
np.random.seed(seed=0)


In [63]:
np.random.seed(seed=1)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

### 3.Vieweing arrays and matrices


In [64]:
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [65]:
a1

array([1, 2, 3, 4])

In [69]:
a2[0]

array([1. , 2. , 3.3])

In [70]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

### 4. Manipulating & comparing arrays


##### Arithmetics

In [71]:
a1

array([1, 2, 3, 4])

In [76]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [78]:
a1+ones

array([2., 3., 4., 5.])

In [80]:
sum(a1)

10

In [86]:
a1.shape


(4,)

In [87]:
a2.shape

(2, 3)

In [81]:
a1*a2

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [100]:
a1p = np.reshape(a1,(2,2))
a2p = np.reshape(a2,(3,2))

In [102]:
a1p*a2p

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

##### Agregation
Agregation = performing the same operation on a number of things

#Use Python's methods(`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`), but if you have to do some methods on a massive data use np

In [104]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.31710151, 0.06814488, 0.16715155, 0.08054059, 0.53021092,
       0.64052803, 0.90996275, 0.10443187, 0.85335217, 0.96705916])

In [105]:
%timeit sum(massive_array)`
%timeit np.sum(massive_array)

8.18 ms ± 375 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
33.6 µs ± 2.48 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
a2 = np.array([[1, 2, 3.3],[4,5,6.5]])
a2

In [106]:
# Standard deviation = a measure of how spread out a group of number is from the meab
np.std(a2)

1.8226964152656422

In [107]:
#Variance = measure of the average degree to which each number is different from the mean
#Higher variance = wider range of numbers
#Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [108]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [110]:
np.var(np.ones(5))

0.0

### Reshaping & transposing

In [111]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [112]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [114]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

### Transpose = switches the axis

In [115]:
a2.shape


(2, 3)

In [116]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [117]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [118]:
a2.T.shape

(3, 2)

### Dot product m

In [131]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [123]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [124]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [126]:
 # Element-wise multiplication (Hadamard product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [133]:
# Dot product (inmultirea de matrici clasica)
mat2.reshape(3,5)
np.dot(mat1,mat2.reshape(3,5))

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [134]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [135]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [136]:
mat2.reshape(3,5)

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

## Dot product example (nut butter sales)


In [141]:
np.random.seed(10)
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[ 9,  4, 15],
       [ 0, 17, 16],
       [17,  8,  9],
       [ 0, 10,  8],
       [ 4, 19, 16]])

In [144]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,index=["Mon","Tues","Wed","Thurs","Fri"],
                            columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales


Almond butter  Peanut butter  Cashew butter
Mon                9              4             15
Tues               0             17             16
Wed               17              8              9
Thurs              0             10              8
Fri                4             19             16

In [159]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [150]:
# Create b;utter_price DataFrame
price_sales = pd.DataFrame(prices.reshape(1,3), index=["Price"],
                          columns=["Almond butter","Peanut butter", "Cashew butter"])
price_sales

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [155]:
prices = prices.reshape(1,3)

In [156]:
prices.shape

(1, 3)

In [157]:
sales_amounts.shape

(5, 3)

In [160]:
sales_amounts.dot(prices)

array([302, 328, 342, 176, 384])

In [163]:
prices.dot(sales_amounts.T)

array([302, 328, 342, 176, 384])

In [166]:
weekly_sales.dot(price_sales.T)

Price
Mon      302
Tues     328
Wed      342
Thurs    176
Fri      384

In [167]:
price_sales.dot(weekly_sales.T)

Mon  Tues  Wed  Thurs  Fri
Price  302   328  342    176  384

In [169]:
weekly_sales["Total ($)"] = weekly_sales.dot(price_sales.T)

In [170]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon                9              4             15        302
Tues               0             17             16        328
Wed               17              8              9        342
Thurs              0             10              8        176
Fri                4             19             16        384

### Comparison Operators

In [173]:
a1 = np.array([1,2,3])

In [174]:
a1

array([1, 2, 3])

In [172]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [175]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [177]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [178]:
a1 != a2

array([[False, False,  True],
       [ True,  True,  True]])

In [179]:
a1 == a2


array([[ True,  True, False],
       [False, False, False]])

In [180]:
a1 < 2

array([ True, False, False])

### Sorting array

In [183]:
random_array_4


array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [184]:
np.sort(random_array_4)

array([[5, 8, 9],
       [0, 0, 5],
       [1, 6, 7],
       [2, 4, 9],
       [2, 4, 5]])

In [185]:
np.argsort(random_array_4)

array([[0, 1, 2],
       [1, 2, 0],
       [0, 2, 1],
       [1, 2, 0],
       [1, 2, 0]])

In [188]:
np.argmin(random_array_4,axis=1)

array([0, 1, 0, 1, 1])

In [189]:
np.argmin(random_array_4)

4

<img src="panda.png"/>

### Turning a image into a NumPy array

In [196]:
from matplotlib.image import imread

In [198]:
panda = imread("panda.png")

In [203]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0