# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array( [ [[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]  ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3.shape

(2, 2, 3)

In [14]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, type(a1), a1.size, a1.dtype, a1.ndim

((3,), numpy.ndarray, 3, dtype('int64'), 1)

In [15]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [16]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
numbers_dataFrame = pd.DataFrame(a2,index=["Index1","Index2"],columns=["i1","i2","i3"])
numbers_dataFrame

i1  i2  i3
Index1   1   2   3
Index2   4   5   6

In [19]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
a_range3 = np.array(range(0,100,3))
a_range3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random1 = np.random.randint(0,10,size=(7,2))
random1

array([[6, 3],
       [3, 2],
       [0, 9],
       [0, 0],
       [7, 0],
       [2, 9],
       [9, 1]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random2 = np.random.random(size=(3,5))
random2

array([[0.3212846 , 0.67044877, 0.58317418, 0.26248516, 0.28722012],
       [0.83053908, 0.27289019, 0.39001607, 0.91300257, 0.2584317 ],
       [0.77898884, 0.17321032, 0.00830815, 0.93430428, 0.21533635]])

In [29]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random3 = np.random.randint(0,10,size=(4,6))
random3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [31]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random4 = np.random.randint(1,10,size=(3,7))
random4
# Find the unique numbers in the array you just created
np.unique(random4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
random4

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [32]:
# Find the 0'th index of the latest array you created
random4[0]

array([7, 8, 3, 1, 4, 2, 8])

In [34]:
# Get the first 2 rows of latest array you created
random4[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [100]:

# Get the first 2 values of the first 2 rows of the latest array
random4[:2,:2] 

array([[7, 8],
       [4, 2]])

In [58]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random5 = np.random.randint(0,10,size=(3,5))
ones5 = np.ones(shape=(3,5),dtype=int)

In [59]:
random5


array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9]])

In [60]:
ones5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
# Add the two arrays together
random5+ones5

array([[ 7,  7,  8,  5,  3],
       [ 8,  6,  3,  1,  3],
       [ 5,  3,  1,  5, 10]])

In [63]:
# Create another array of ones of shape (5, 3)
ones6 = np.ones(shape=(5,3),dtype=int)
ones6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
# Try add the array of ones and the other most recent array together
ones5+ones6.T


array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [68]:
# Create another array of ones of shape (3, 5)
ones7 = np.ones(shape=(3,5),dtype=int)
ones7

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [72]:
# Subtract the new array of ones from the other most recent array
ones5-ones7

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [73]:
# Multiply the ones array with the latest array
random5*ones7

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9]])

In [74]:
# Take the latest array to the power of 2 using '**'
random5**2

array([[36, 36, 49, 16,  4],
       [49, 25,  4,  0,  4],
       [16,  4,  0, 16, 81]])

In [75]:
# Do the same thing with np.square()
np.square(random5)

array([[36, 36, 49, 16,  4],
       [49, 25,  4,  0,  4],
       [16,  4,  0, 16, 81]])

In [76]:
# Find the mean of the latest array using np.mean()
np.mean(random5)

4.0

In [77]:
# Find the maximum of the latest array using np.max()
np.max(random5)

9

In [78]:
# Find the minimum of the latest array using np.min()
np.min(random5)

0

In [80]:
# Find the standard deviation of the latest array
random5.std()

2.581988897471611

In [81]:
# Find the variance of the latest array
random5.var()

6.666666666666667

In [82]:
random5.shape

(3, 5)

In [83]:
# Reshape the latest array to (3, 5, 1)
random5.reshape(3,5,1)

array([[[6],
        [6],
        [7],
        [4],
        [2]],

       [[7],
        [5],
        [2],
        [0],
        [2]],

       [[4],
        [2],
        [0],
        [4],
        [9]]])

In [84]:
# Transpose the latest array
random5.T

array([[6, 7, 4],
       [6, 5, 2],
       [7, 2, 0],
       [4, 0, 4],
       [2, 2, 9]])

What does the transpose do?

In [85]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random33 = np.random.randint(0,10,size=(3,3))
random32 = np.random.randint(0,10,size=(3,2))

In [86]:
# Perform a dot product on the two newest arrays you created
random33.dot(random32)

array([[ 78, 108],
       [ 87, 102],
       [ 27,  42]])

In [89]:
random32.T.dot(random33)

array([[ 90,  72,  45],
       [114,  78,  62]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
pass

In [36]:
# Perform a dot product on the two newest arrays you created
pass

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
pass

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
pass

In [39]:
# Compare the two arrays with '>'
pass

What happens when you compare the arrays with `>`?

In [40]:

# Compare the two arrays with '>='
pass

In [41]:
# Find which elements of the first array are greater than 7
>7

In [42]:
# Which parts of each array are equal? (try using '==')
pass

In [91]:
# Sort one of the arrays you just created in ascending order
random33.sort()
random33

array([[6, 6, 8],
       [2, 9, 9],
       [0, 3, 6]])

In [95]:
# Sort the indexes of one of the arrays you just created
random32.argsort()

array([[0, 1],
       [0, 1],
       [0, 1]])

In [98]:
# Find the index with the maximum value in one of the arrays you've created
random33.argmax(axis=1)

array([2, 1, 2])

In [99]:
# Find the index with the minimum value in one of the arrays you've created
random33.argmin()

6

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
pass

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
pass

In [101]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.8084936 , -0.50175704,  0.91540212,  0.32875111, -0.5297602 ],
       [ 0.51326743,  0.09707755,  0.96864499, -0.70205309, -0.32766215],
       [-0.39210815, -1.46351495,  0.29612028,  0.26105527,  0.00511346]])

In [103]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.